-- 1. Crear la base de datos (si no existe)
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'EstudiantesDB')
BEGIN
    CREATE DATABASE [EstudiantesDB];
    PRINT 'Base de datos EstudiantesDB creada.';
END
GO

-- 2. Usar la BD
USE [EstudiantesDB];
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 22/06/2025 02:14:11 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estudiantes]    Script Date: 22/06/2025 02:14:11 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estudiantes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombres] [nvarchar](max) NOT NULL,
	[Apellidos] [nvarchar](max) NOT NULL,
	[FechaNacimiento] [datetime2](7) NOT NULL,
	[Direccion] [nvarchar](max) NOT NULL,
	[Sexo] [nvarchar](max) NOT NULL,
	[CURP] [nvarchar](18) NOT NULL,
	[Telefono] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[Carrera] [nvarchar](max) NOT NULL,
	[EsBecado] [bit] NOT NULL,
	[Modalidad] [nvarchar](max) NOT NULL,
	[DescripcionPersonal] [nvarchar](max) NULL,
	[TieneMascotas] [bit] NOT NULL,
	[TipoMascotas] [nvarchar](max) NULL,
	[HorarioComida] [nvarchar](max) NULL,
 CONSTRAINT [PK_Estudiantes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20250620000822_Inicial', N'9.0.6')
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20250621085659_AgregarCampoEsBecado', N'9.0.6')
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20250621214506_AddOptionalFields', N'9.0.6')
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20250621231716_PermitirNullCamposOpcionales', N'9.0.6')
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20250621234602_ConfiguracionCamposOpcionales', N'9.0.6')
GO
SET IDENTITY_INSERT [dbo].[Estudiantes] ON 

INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (4, N'Diana Laura', N'Mendez Ruperto', CAST(N'2001-11-14T00:00:00.0000000' AS DateTime2), N'Calle Vázquez Gómez 803', N'Femenino', N'MERD011114MVZNPNA7', N'9241129375', N'dl.mendezruperto@gmail.com', N'Ingeniería en Sistemas', 0, N'Presencial', N'Atleta', 0, N'Gate', N'2 pm')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (23, N'Alicia', N'Ruperto', CAST(N'1980-03-06T00:00:00.0000000' AS DateTime2), N'Salsipuedes 20', N'Femenino', N'LOMA900101HDFNRR00', N'9242438822', N'ali@gmail.com', N'Derecho', 1, N'Ambos', N'Running', 1, N'Perro', N'3 pm')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (25, N'Dalia', N'Fuentes', CAST(N'2003-09-29T00:00:00.0000000' AS DateTime2), N'Veracruz 38', N'Femenino', N'FUCD290903MVZABC09', N'2711823141', N'krookodile28@gmail.com', N'Psicología', 0, N'Online', N'Padecimiento', 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (27, N'Ana', N'Gómez', CAST(N'2001-08-20T00:00:00.0000000' AS DateTime2), N'Av. Principal #67', N'Femenino', N'ANGO010820MDFXYZ02', N'5511223344', N'ana.gomez@email.com', N'Psicología', 1, N'Online', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (28, N'Luis', N'Martínez', CAST(N'1999-11-10T00:00:00.0000000' AS DateTime2), N'Calle Luna #89', N'Masculino', N'LUMT991110HDFLMN03', N'5533445566', N'luis.martinez@email.com', N'Derecho', 0, N'Ambos', N'Interesado en derecho internacional', 1, N'Gato', N'13:30-14:30')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (29, N'María', N'Rodríguez', CAST(N'2002-03-25T00:00:00.0000000' AS DateTime2), N'Av. Sol #12', N'Femenino', N'MARD020325MDFRSD04', N'5544556677', N'maria.rodriguez@email.com', N'Biología', 1, N'Presencial', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (30, N'Carlos', N'Sánchez', CAST(N'2000-07-30T00:00:00.0000000' AS DateTime2), N'Calle Estrella #34', N'Masculino', N'CASA000730HDFSNC05', N'5566778899', N'carlos.sanchez@email.com', N'Administración', 0, N'Online', N'Emprendedor', 1, N'Perro', N'14:00-15:00')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (31, N'Laura', N'Hernández', CAST(N'2001-01-12T00:00:00.0000000' AS DateTime2), N'Av. Jardín #56', N'Femenino', N'LAHE010112MDFHRL06', N'5577889900', N'laura.hernandez@email.com', N'Educación', 1, N'Ambos', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (32, N'Pedro', N'Díaz', CAST(N'1999-09-05T00:00:00.0000000' AS DateTime2), N'Calle Río #78', N'Masculino', N'PEDI990905HDFDZP07', N'5588990011', N'pedro.diaz@email.com', N'Matemáticas', 0, N'Presencial', N'Amante del álgebra', 1, N'Tortuga', N'12:30-13:30')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (33, N'Sofía', N'López', CAST(N'2002-12-18T00:00:00.0000000' AS DateTime2), N'Av. Bosque #90', N'Femenino', N'SOLO021218MDFLPS08', N'5599001122', N'sofia.lopez@email.com', N'Química', 1, N'Online', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (34, N'Jorge', N'Ramírez', CAST(N'2000-04-22T00:00:00.0000000' AS DateTime2), N'Calle Montaña #11', N'Masculino', N'JORA000422HDFRMJ09', N'5500112233', N'jorge.ramirez@email.com', N'Economía', 0, N'Ambos', N'Interesado en macroeconomía', 1, N'Perro', N'13:00-14:00')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (35, N'Diana', N'Flores', CAST(N'2001-06-14T00:00:00.0000000' AS DateTime2), N'Av. Valle #22', N'Femenino', N'DIFL010614MDFLRD10', N'5511223344', N'diana.flores@email.com', N'Mercadotecnia', 1, N'Presencial', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (36, N'Ricardo', N'Vargas', CAST(N'1999-02-28T00:00:00.0000000' AS DateTime2), N'Calle Flor #33', N'Masculino', N'RIVA990228HDFVGR11', N'5522334455', N'ricardo.vargas@email.com', N'Ingeniería en Sistemas', 0, N'Online', N'Desarrollador full-stack', 1, N'Gato', N'14:30-15:30')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (37, N'Elena', N'Cruz', CAST(N'2002-10-08T00:00:00.0000000' AS DateTime2), N'Av. Piedra #44', N'Femenino', N'ELCR021008MDFCZE12', N'5533445566', N'elena.cruz@email.com', N'Psicología', 1, N'Ambos', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (38, N'Fernando', N'Morales', CAST(N'2000-07-19T00:00:00.0000000' AS DateTime2), N'Calle Agua #55', N'Masculino', N'FEMO000719HDFMRF13', N'5544556677', N'fernando.morales@email.com', N'Derecho', 0, N'Presencial', N'Especializado en penal', 1, N'Perro', N'12:00-13:00')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (39, N'Gabriela', N'Ortiz', CAST(N'2001-03-03T00:00:00.0000000' AS DateTime2), N'Av. Cielo #66', N'Femenino', N'GAOR010303MDFRTG14', N'5555667788', N'gabriela.ortiz@email.com', N'Biología', 1, N'Online', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (40, N'Diego', N'Gutiérrez', CAST(N'1999-08-11T00:00:00.0000000' AS DateTime2), N'Calle Nube #77', N'Masculino', N'DIGU990811HDFGTD15', N'5566778899', N'diego.gutierrez@email.com', N'Administración', 0, N'Ambos', N'Enfocado en RH', 1, N'Pájaro', N'13:00-14:00')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (41, N'Patricia', N'Ruiz', CAST(N'2002-05-27T00:00:00.0000000' AS DateTime2), N'Av. Viento #88', N'Femenino', N'PARU020527MDFRZP16', N'5577889900', N'patricia.ruiz@email.com', N'Educación', 1, N'Presencial', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (42, N'Roberto', N'Mendoza', CAST(N'2000-11-09T00:00:00.0000000' AS DateTime2), N'Calle Lluvia #99', N'Masculino', N'ROME001109HDFMDR17', N'5588990011', N'roberto.mendoza@email.com', N'Matemáticas', 0, N'Online', N'Investigador en teoría de números', 1, N'Perro', N'14:00-15:00')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (43, N'Lucía', N'Guerrero', CAST(N'2001-09-21T00:00:00.0000000' AS DateTime2), N'Av. Rayo #10', N'Femenino', N'LUGU010921MDFGRL18', N'5599001122', N'lucia.guerrero@email.com', N'Química', 1, N'Ambos', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (44, N'José', N'Reyes', CAST(N'1999-12-30T00:00:00.0000000' AS DateTime2), N'Calle Trueno #20', N'Masculino', N'JORE991230HDFRSJ19', N'5500112233', N'jose.reyes@email.com', N'Economía', 0, N'Presencial', N'Analista financiero', 1, N'Gato', N'12:30-13:30')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (45, N'Adriana', N'Medina', CAST(N'2002-04-05T00:00:00.0000000' AS DateTime2), N'Av. Relámpago #30', N'Femenino', N'ADME020405MDFMDA20', N'5511223344', N'adriana.medina@email.com', N'Mercadotecnia', 1, N'Online', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (46, N'Alejandro', N'Silva', CAST(N'2000-01-15T00:00:00.0000000' AS DateTime2), N'Calle Arcoíris #40', N'Masculino', N'AESI000115HDFSLA21', N'5522334455', N'alejandro.silva@email.com', N'Ingeniería en Sistemas', 0, N'Ambos', N'Especialista en IA', 1, N'Perro', N'13:00-14:00')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (47, N'Carmen', N'Rojas', CAST(N'2001-07-22T00:00:00.0000000' AS DateTime2), N'Av. Aurora #50', N'Femenino', N'CARO010722MDFRJC22', N'5533445566', N'carmen.rojas@email.com', N'Psicología', 1, N'Presencial', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (48, N'Miguel', N'Acosta', CAST(N'1999-10-18T00:00:00.0000000' AS DateTime2), N'Calle Eclipse #60', N'Masculino', N'MIAC991018HDFCSM23', N'5544556677', N'miguel.acosta@email.com', N'Derecho', 0, N'Online', N'Derecho corporativo', 1, N'Tortuga', N'14:30-15:30')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (49, N'Teresa', N'Mejía', CAST(N'2002-02-14T00:00:00.0000000' AS DateTime2), N'Av. Galaxia #70', N'Femenino', N'TEME020214MDFMJT24', N'5555667788', N'teresa.mejia@email.com', N'Biología', 1, N'Ambos', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (50, N'Francisco', N'Castañeda', CAST(N'2000-06-28T00:00:00.0000000' AS DateTime2), N'Calle Universo #80', N'Masculino', N'FRCA000628HDFCSF25', N'5566778899', N'francisco.castaneda@email.com', N'Administración', 0, N'Presencial', N'Consultor empresarial', 1, N'Perro', N'12:00-13:00')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (51, N'Verónica', N'Juárez', CAST(N'2001-12-03T00:00:00.0000000' AS DateTime2), N'Av. Planeta #90', N'Femenino', N'VEJU011203MDFJRV26', N'5577889900', N'veronica.juarez@email.com', N'Educación', 1, N'Online', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (52, N'Raúl', N'Núñez', CAST(N'1999-04-17T00:00:00.0000000' AS DateTime2), N'Calle Cometa #100', N'Masculino', N'RUNU990417HDFNZR27', N'5588990011', N'raul.nunez@email.com', N'Matemáticas', 0, N'Ambos', N'Geometría diferencial', 1, N'Gato', N'13:30-14:30')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (53, N'Isabel', N'Salazar', CAST(N'2002-08-09T00:00:00.0000000' AS DateTime2), N'Av. Asteroide #110', N'Femenino', N'ISSA020809MDFSLI28', N'5599001122', N'isabel.salazar@email.com', N'Química', 1, N'Presencial', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (54, N'Arturo', N'Vega', CAST(N'2000-03-12T00:00:00.0000000' AS DateTime2), N'Calle Nebulosa #120', N'Masculino', N'ARVE000312HDFVGA29', N'5500112233', N'arturo.vega@email.com', N'Economía', 0, N'Online', N'Econometría', 1, N'Pez', N'14:00-15:00')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (55, N'Daniela', N'Pacheco', CAST(N'2001-05-26T00:00:00.0000000' AS DateTime2), N'Av. Supernova #130', N'Femenino', N'DAPA010526MDFPCD30', N'5511223344', N'daniela.pacheco@email.com', N'Mercadotecnia', 1, N'Ambos', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (56, N'Oscar', N'Campos', CAST(N'1999-09-07T00:00:00.0000000' AS DateTime2), N'Calle Agujero Negro #140', N'Masculino', N'OSCA990907HDFCMO31', N'5522334455', N'oscar.campos@email.com', N'Ingeniería en Sistemas', 0, N'Presencial', N'Desarrollo móvil', 1, N'Perro', N'12:30-13:30')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (57, N'Rosa', N'Delgado', CAST(N'2002-01-20T00:00:00.0000000' AS DateTime2), N'Av. Quasar #150', N'Femenino', N'RODE020120MDFDLR32', N'5533445566', N'rosa.delgado@email.com', N'Psicología', 1, N'Online', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (58, N'Héctor', N'Maldonado', CAST(N'2000-07-04T00:00:00.0000000' AS DateTime2), N'Calle Púlsar #160', N'Masculino', N'HEMA000704HDFMLH33', N'5544556677', N'hector.maldonado@email.com', N'Derecho', 0, N'Ambos', N'Derecho penal', 1, N'Serpiente', N'13:00-14:00')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (59, N'Silvia', N'Cervantes', CAST(N'2001-11-15T00:00:00.0000000' AS DateTime2), N'Av. Materia Oscura #170', N'Femenino', N'SICE011115MDFCVS34', N'5555667788', N'silvia.cervantes@email.com', N'Biología', 1, N'Presencial', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (60, N'Javier', N'Quintero', CAST(N'1999-02-28T00:00:00.0000000' AS DateTime2), N'Calle Energía #180', N'Masculino', N'JAQU990228HDFQTJ35', N'5566778899', N'javier.quintero@email.com', N'Administración', 0, N'Online', N'Logística', 1, N'Perro', N'14:30-15:30')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (61, N'Alicia', N'Zamora', CAST(N'2002-06-10T00:00:00.0000000' AS DateTime2), N'Av. Gravedad #190', N'Femenino', N'ALZA020610MDFZMA36', N'5577889900', N'alicia.zamora@email.com', N'Educación', 1, N'Ambos', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (62, N'Manuel', N'Rosales', CAST(N'2000-10-24T00:00:00.0000000' AS DateTime2), N'Calle Espacio #200', N'Masculino', N'MARO001024HDFRSM37', N'5588990011', N'manuel.rosales@email.com', N'Matemáticas', 0, N'Presencial', N'Topología', 1, N'Gato', N'12:00-13:00')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (63, N'Claudia', N'Miranda', CAST(N'2001-04-06T00:00:00.0000000' AS DateTime2), N'Av. Tiempo #210', N'Femenino', N'CLMI010406MDFMRC38', N'5599001123', N'claudia.miranda@email.com', N'Derecho', 1, N'Online', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (64, N'Eduardo', N'Navarro', CAST(N'1999-08-19T00:00:00.0000000' AS DateTime2), N'Calle Dimensión #220', N'Masculino', N'EDNA990819HDFNVE39', N'5500112233', N'eduardo.navarro@email.com', N'Economía', 0, N'Ambos', N'Microeconomía', 1, N'Araña', N'13:30-14:30')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (65, N'Beatriz', N'Espinoza', CAST(N'2002-12-02T00:00:00.0000000' AS DateTime2), N'Av. Singularidad #230', N'Femenino', N'BEES021202MDFSPB40', N'5511223344', N'beatriz.espinoza@email.com', N'Mercadotecnia', 1, N'Presencial', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (66, N'Sergio', N'Valdez', CAST(N'2000-05-16T00:00:00.0000000' AS DateTime2), N'Calle Multiverso #240', N'Masculino', N'SEVA000516HDFVLS41', N'5522334455', N'sergio.valdez@email.com', N'Ingeniería en Sistemas', 0, N'Online', N'Blockchain', 1, N'Perro', N'14:00-15:00')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (67, N'Natalia', N'Franco', CAST(N'2001-09-29T00:00:00.0000000' AS DateTime2), N'Av. Infinito #250', N'Femenino', N'NAFR010929MDFFRN42', N'5533445566', N'natalia.franco@email.com', N'Psicología', 1, N'Ambos', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (68, N'Alberto', N'Ríos', CAST(N'1999-01-11T00:00:00.0000000' AS DateTime2), N'Calle Cuántica #260', N'Masculino', N'ALRI990111HDFRSA43', N'5544556677', N'alberto.rios@email.com', N'Derecho', 0, N'Presencial', N'Derecho ambiental', 1, N'Hamster', N'12:30-13:30')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (69, N'Mariana', N'Barrera', CAST(N'2002-07-25T00:00:00.0000000' AS DateTime2), N'Av. Relatividad #270', N'Femenino', N'MABA020725MDFBRM44', N'5555667788', N'mariana.barrera@email.com', N'Biología', 1, N'Online', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (70, N'Guillermo', N'Aguilar', CAST(N'2000-11-08T00:00:00.0000000' AS DateTime2), N'Calle Entropía #280', N'Masculino', N'GUAG001108HDFGLG45', N'5566778899', N'guillermo.aguilar@email.com', N'Administración', 0, N'Ambos', N'Estrategia corporativa', 1, N'Perro', N'13:00-14:00')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (71, N'Lorena', N'Tapia', CAST(N'2001-03-21T00:00:00.0000000' AS DateTime2), N'Av. Caos #290', N'Femenino', N'LOTA010321MDFTPL46', N'5577889900', N'lorena.tapia@email.com', N'Educación', 1, N'Presencial', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (72, N'Rodrigo', N'Méndez', CAST(N'1999-07-04T00:00:00.0000000' AS DateTime2), N'Calle Fractal #300', N'Masculino', N'ROME990704HDFMZR47', N'5588990011', N'rodrigo.mendez@email.com', N'Matemáticas', 0, N'Online', N'Teoría de juegos', 1, N'Iguana', N'14:30-15:30')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (73, N'Gabriela', N'Cisneros', CAST(N'2002-10-17T00:00:00.0000000' AS DateTime2), N'Av. Algoritmo #310', N'Femenino', N'GACI021017MDFCSG48', N'5599001122', N'gabriela.cisneros@email.com', N'Química', 1, N'Ambos', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (74, N'Felipe', N'Orozco', CAST(N'2000-02-29T00:00:00.0000000' AS DateTime2), N'Calle Tensor #320', N'Masculino', N'FEOR000229HDFRLF49', N'5500112233', N'felipe.orozco@email.com', N'Economía', 0, N'Presencial', N'Economía conductual', 1, N'Perro', N'12:00-13:00')
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (75, N'Jimena', N'Galván', CAST(N'2001-08-12T00:00:00.0000000' AS DateTime2), N'Av. Matriz #330', N'Femenino', N'JIGA010812MDFGLJ50', N'5511223344', N'jimena.galvan@email.com', N'Mercadotecnia', 1, N'Online', NULL, 0, NULL, NULL)
INSERT [dbo].[Estudiantes] ([Id], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Sexo], [CURP], [Telefono], [Email], [Carrera], [EsBecado], [Modalidad], [DescripcionPersonal], [TieneMascotas], [TipoMascotas], [HorarioComida]) VALUES (76, N'Daniel', N'Benitez', CAST(N'2003-05-12T00:00:00.0000000' AS DateTime2), N'Rio Blanco', N'Masculino', N'LOMA900101HDFNRR00', N'2721112233', N'daniel@mail.com', N'Educación', 1, N'Presencial', N'Atleta', 0, NULL, NULL)
SET IDENTITY_INSERT [dbo].[Estudiantes] OFF
GO
ALTER TABLE [dbo].[Estudiantes] ADD  CONSTRAINT [DF_TieneMascotas]  DEFAULT ((0)) FOR [TieneMascotas]
GO

